# Generated by Django 5.1.4 on 2025-04-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_rename_dob_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenomeUpload',
        ),
    ]
