# Generated by Django 5.1.4 on 2025-05-12 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_predictionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictionresult',
            name='original_file',
        ),
        migrations.RemoveField(
            model_name='predictionresult',
            name='predicted_diseases',
        ),
    ]
